### ISSUE TITLE
Telegram ignores second slash

### ISSUE THREAD

**Issue by jcserracampos** [zws-im/zws#15]
This is probably a Telegram issue but just wanted to let you know.

**Comment by pizzafox** [comment]
We're aware of the Telegram bug. Most likely it's Telegram filtering which characters are allowed to be in a URL.

**Comment by pizzafox** [comment]
Fixed in b39897e529f0bce3bc784b42ff63d0f75a2947b1.

**Comment by pizzafox** [comment]
When I tested this I used a URL that happened to only have `U+200C` in the short ID. URLs still do not fully work on Telegram.

**Comment by pizzafox** [comment]
Fixed in 97bbe60.

**Comment by jcserracampos** [comment]
Thank you!

**Comment by cs16lover** [comment]
Still doesnt works un Telegram
