### ISSUE TITLE
Are there ratelimits?

### ISSUE THREAD

**Issue by XCanG** [zws-im/zws#19]
I want use your service for posting `magnet:` links to torrent on Discord. Since Discord don't allowing creating links from magnet protocol, using https instead would be only solution. However it may require to follow ratelimits if there any.

_P.S. another idea for not filling regular database pool is allowing using names (optional) along with url, e.g. in my case using name `magnet` → `https://zws.im/magnet/` will use it's own pool of urls, but it also may be something else, like `youtube`, `game`, `movie` or even smaller category `JohnURLs`, `SpiderMan`, ..._

**Comment by pizzafox** [comment]
I haven't written any rate limiting code (which may be a mistake) but Firebase Functions might. I know that if you send the same request body several times in a row it will respond with a code `304` Not Modified.
