### ISSUE TITLE
Help:About zws _Heroku configuration: SHORT_CHARS

### ISSUE THREAD

**Issue by HiChen404** [zws-im/zws#235]
# About Heroku configuration

There’s nothing wrong with the procedure, but I’d like to ask a question:

![image](https://user-images.githubusercontent.com/58675561/132097582-32cc8b11-4038-4b06-99c9-d1f2cbe5fa69.png)
If I leave "SHORT_CHARS" configuration blank  , my Self-hosting works result will be like this :
```json
{
    "short": "iBeXr",
    "url": "https://weeqeqewx.herokuapp.com/iBeXr"
}
```
That’s not how I wanted it to be.It not contains  zero-width space.

But I don't know how to fill in  this configuration, What’s the format?

Please give some advice ! Thank you !

**Comment by jonahsnider** [comment]
Set that field to be a JSON array of each character:

```json
["a", "b", "c"]
```

Just replace those values with zero-width characters.

Currently zws.im uses these characters:
```json
["\u200c","\u200d","\udb40\udc61","\udb40\udc62","\udb40\udc63","\udb40\udc64","\udb40\udc65","\udb40\udc66","\udb40\udc67","\udb40\udc68","\udb40\udc69","\udb40\udc6a","\udb40\udc6b","\udb40\udc6c","\udb40\udc6d","\udb40\udc6e","\udb40\udc6f","\udb40\udc70","\udb40\udc71","\udb40\udc72","\udb40\udc73","\udb40\udc74","\udb40\udc75","\udb40\udc76","\udb40\udc77","\udb40\udc78","\udb40\udc79","\udb40\udc7a","\udb40\udc7f"]```

**Comment by HiChen404** [comment]
It works ! Thank you very much indeed!
