### ISSUE TITLE
The Compose file './docker-compose.yml' is invalid because

### ISSUE THREAD

**Issue by Kirill** [zws-im/zws#262]
docker-compose can't execute:
```
The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for volumes: 'db'
Unsupported config option for services: 'db'
```
Docker version 20.10.8, build 3967b7d
docker-compose version 1.25.0, build unknown
5.8.0-1038-oracle #39~20.04.1-Ubuntu SMP Mon Aug 2 13:33:34 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux

**Comment by jonahsnider** [comment]
Unable to reproduce with Docker Compose `v2.0.0-rc.3`, try upgrading to `v2` and seeing if that fixes the problem.
