### ISSUE TITLE
scam reporting

### ISSUE THREAD

**Issue by SubGplayz** [zws-im/zws#685]
found a discord nsfw verify scam using this
![image](https://github.com/zws-im/zws/assets/68687751/e8373b4e-5505-49f1-8b18-b080dc3b581b)
some sort of reporting thing on the main page would be a good addition btw

**Comment by jonahsnider** [comment]
Thanks for reporting, I have blocked the domain to prevent it from being used on ZWS in the future.

**Comment by honesty-aries** [comment]
> Thanks for reporting, I have blocked the domain to prevent it from being used on ZWS in the future.

they are still using it
