### ISSUE TITLE
Contact request - collaboration on abuse reporting 

### ISSUE THREAD

**Issue by BlackWolfWoof** [zws-im/zws#710]
TLDR; your link shortner is heavily abused. Please a take care of the abuse.

Several people including me have tried reaching out to you due to abuse of your link shortner but have yet to receive any kind of reply. The url i provided in my email has successfully been blocked but the volume of urls i have every day makes email reports very impractical.
I'd be happy if you are willing to discuss a more direct or even automated way of reporting the urls to you in the near future.

**Comment by BlackWolfWoof** [comment]
I'd also be happy to offer an API which is offers a list of phishing domains are partly used on your link shorter which makes blocking the domains a lot easier for you :)

**Comment by jonahsnider** [comment]
Hi,

I'm trying my best to keep up with the reports coming in, but unfortunately I've been super busy the past few days and haven't been keeping up with it very well. The volume of reports is also A Lot. I'll sit down today and go through the emails I've been getting + look at some of the internal analytics I've got.

I am in the midst of coming up with a better system for preventing abuse (integrating with some APIs for flagging malicious URLs). It'll be released early next week once I'm less busy.

Thanks,
Jonah
