### ISSUE TITLE
Some Content overlap on header

### ISSUE THREAD

**Issue by ashishairtkt** [zws-im/zws#742]
![Screenshot 2024-06-19 200717](https://github.com/zws-im/zws/assets/117058402/dd2bdec0-5911-4f06-8fe2-0a660297bc67)

**Comment by jonahsnider** [comment]
Closed in 5d262a6094917fedf3817c3699789bfbdd43fd11

**Comment by ashishairtkt** [comment]
Great
Thanks & Regards
Ashish Singh Rathod
